image: makeappdev/cpp-dev       # This is the docker image that contains all required tools

stages:
  - build
  - test

cpp_build_test_gcc:             # This is a CI job
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
    - make test
    - make coverage

check:
  stage: test
  script:
    - find . -type f -regex '.*\.\(cpp\|hpp\|cu\|c\|cc\|h\)' -not \( -path '*/venv/*' -o -path '*/build/*' -o -path '*/cmake-build-debug/*' \) | xargs clang-format-10 --style=file -i --dry-run --Werror
